#!/usr/bin/env python3

import argparse
import json
import re
from pathlib import Path


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def strip_html(text):
    return re.sub(r"<[^>]+>", "", text)


def slugify(text):
    text = strip_html(text)
    text = text.replace("&", " ")
    text = text.replace("/", " ")
    text = text.replace("—", " ")
    text = text.replace("–", " ")
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    text = re.sub(r"-{2,}", "-", text)
    return text


def assign_slugs(sections, seen=None):
    if seen is None:
        seen = {}
    for section in sections:
        base_slug = slugify(section["title"])
        count = seen.get(base_slug, 0)
        section["slug"] = base_slug if count == 0 else f"{base_slug}-{count}"
        seen[base_slug] = count + 1
        assign_slugs(section.get("subsections", []), seen)


def render_image_tag(item):
    return f'<img src="{item["image"]}" alt="{item.get("alt", "")}">'


def render_badge_row(items):
    rendered = []
    for item in items:
        image = render_image_tag(item)
        href = item.get("href")
        rendered.append(f'<a href="{href}">{image}</a>' if href else image)
    return "<p>\n  " + "\n  ".join(rendered) + "\n</p>"


def render_text_nav(items):
    links = [f'<a href="{item["href"]}">{item["alt"]}</a>' for item in items]
    return "<p><sub>" + " · ".join(links) + "</sub></p>"


def render_table(table):
    headers = table["headers"]
    rows = table["rows"]
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def iter_toc(sections, depth=0, max_depth=1):
    items = []
    for section in sections:
        items.append((depth, section["title"], section["slug"]))
        if depth < max_depth:
            items.extend(iter_toc(section.get("subsections", []), depth + 1, max_depth))
    return items


def render_toc(sections):
    lines = [
        "## Table of Contents",
        "",
        "<details open>",
        "<summary><strong>Browse the list</strong></summary>",
        "",
    ]
    for depth, title, slug in iter_toc(sections):
        indent = "  " * depth
        lines.append(f"{indent}- [{title}](#{slug})")
    lines.extend(["", "</details>"])
    return "\n".join(lines)


def render_section_nav(subsections, label):
    if not subsections:
        return ""
    links = [f'[{subsection["title"]}](#{subsection["slug"]})' for subsection in subsections]
    return f"**{label}:** " + " · ".join(links)


def render_block(block, tables):
    if block["type"] == "markdown":
        return block["text"]
    if block["type"] == "table":
        return render_table(tables[block["ref"]])
    raise ValueError(f"Unsupported block type: {block['type']}")


def render_section(section, tables, meta, depth=0):
    heading_level = min(2 + depth, 6)
    heading = "#" * heading_level + f" {section['title']}"
    parts = [heading]

    subsections = section.get("subsections", [])
    if depth == 0 and subsections:
        parts.append("")
        parts.append(render_section_nav(subsections, "In this section"))
    elif depth == 1 and subsections:
        parts.append("")
        parts.append(render_section_nav(subsections, "Subtopics"))

    for block in section.get("blocks", []):
        parts.append("")
        parts.append(render_block(block, tables))

    for subsection in subsections:
        parts.append("")
        parts.append(render_section(subsection, tables, meta, depth + 1))

    if depth == 0 and section["title"] != "License":
        back_to_top = meta["back_to_top"]
        parts.append("")
        parts.append(f'<p align="right"><a href="{back_to_top["href"]}">{back_to_top["label"]}</a></p>')

    return "\n".join(parts)


def render_header(meta):
    hero_image = meta["hero_image"]
    lines = [
        "<!-- This file is generated by scripts/generate_awesome_readme.py. -->",
        "<!-- Edit data/meta.json, data/content.json, and data/tables.json, then regenerate README.md. -->",
        "",
        '<div align="center">',
        "",
        f"# {meta['title']}",
        f'<img width="1024" alt="{hero_image["alt"]}" src="{hero_image["src"]}" />',
        "",
        f'<p><strong>{meta["subtitle"]}</strong><br/><sub>{meta["tagline"]}</sub></p>',
        "",
        render_badge_row(meta["badges"]),
        "",
        render_badge_row(meta["focus_badges"]),
        "",
        render_badge_row(meta["nav_buttons"]),
        "",
        render_text_nav(meta["nav_buttons"]),
        "",
        "</div>",
    ]
    return "\n".join(lines)


def build_readme(meta, content, tables):
    sections = content["sections"]
    assign_slugs(sections)
    rendered_sections = []
    for index, section in enumerate(sections):
        if index == 0:
            rendered_sections.append(render_section(section, tables, meta))
        else:
            rendered_sections.append("---\n\n" + render_section(section, tables, meta))

    document = [
        render_header(meta),
        "",
        render_toc(sections),
        "",
        "\n\n".join(rendered_sections),
    ]
    text = "\n".join(document).strip() + "\n"
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def main():
    parser = argparse.ArgumentParser(description="Generate README.md from structured JSON data.")
    parser.add_argument("--meta", required=True)
    parser.add_argument("--content", required=True)
    parser.add_argument("--tables", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    meta = load_json(args.meta)
    content = load_json(args.content)
    tables = load_json(args.tables)
    readme = build_readme(meta, content, tables)
    Path(args.output).write_text(readme, encoding="utf-8")


if __name__ == "__main__":
    main()
